name: build

on:
  push:
  pull_request:
  schedule: 
    - cron: '0 6 * * *' # every day at 6:00
    - cron: '30 11 * * 5' # Fridays 11:30 (before the ctapipe meeting)

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  dinghy:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dinghy
        run: |
          python -m pip install -U dinghy pyyaml

      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m dinghy
          python write_index.py

      - name: Deploy to gihub pages
        # only run on main
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          single-commit: true
