name: build

on:
  push:
  pull_request:
  schedule: 
    - cron: '0 6 * * *' # every day at 6:00
    # Fridays, 9:45 and 10:45 UTC to have it up-to-date for the ctapipe meeting in CEST and CET
    - cron: '45 9,10 * * 5'

concurrency:
  group: "pages"
  cancel-in-progress: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  pages: write
  contents: write
  id-token: write

jobs:
  dinghy:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dinghy
        run: |
          python -m pip install -U dinghy pyyaml

      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python write_index.py
          python -m dinghy
          touch build/.nojekyll

      - name: Deploy to gihub pages
        # only run on main
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          single-commit: true
